env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  max-len:
    - error
    - code: 120
      tabWidth: 2
      ignoreUrls: true
      ignoreComments: false
      ignoreTrailingComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
